### PR TITLE
Closes #1097. Fixes the feed settings being reuploaded after every refresh

### LINKED ISSUE #1097: Feeds are reuploaded after every refresh
1) Refresh feeds
2) Get a POST to /settings on the next sync (with there actually being any new data)

### PR DESCRIPTION
**Pull request by adomasven**

### CODE REVIEW

File: chrome/content/zotero/xpcom/data/feed.js [hunk 1]
```diff
@@ -290,6 +290,10 @@ Zotero.Feed.prototype._saveData = Zotero.Promise.coroutine(function* (env) {
 });
 
 Zotero.Feed.prototype._finalizeSave = Zotero.Promise.coroutine(function* (env) {
+	let criticalDataChanged = ['_feedName', '_feedCleanupAfter', '_feedRefreshInterval'].reduce(function(prev, cur) {
+		return prev || this._changed[cur];
+	}.bind(this), false);
+
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/data/feed.js]: Seems like `.some()` would be more appropriate here.

File: chrome/content/zotero/xpcom/data/feed.js [hunk 2]
```diff
@@ -290,6 +290,10 @@ Zotero.Feed.prototype._saveData = Zotero.Promise.coroutine(function* (env) {
 });
 
 Zotero.Feed.prototype._finalizeSave = Zotero.Promise.coroutine(function* (env) {
+	let criticalDataChanged = ['_feedName', '_feedCleanupAfter', '_feedRefreshInterval'].reduce(function(prev, cur) {
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/data/feed.js]: `critical` is a little alarming. `syncedDataChanged`?
