### PR TITLE
Fix PMID and arXiv identifiers extraction

### LINKED ISSUE #1378: Make PMID extraction stricter
https://forums.zotero.org/discussion/69134/will-add-by-identifier-gobble-up-anything-and-output-random-new-items

### PR DESCRIPTION
**Pull request by mrtcode**
Fix #1378

### CODE REVIEW

File: test/tests/utilities_internalTest.js [hunk 1]
```diff
@@ -147,15 +147,20 @@ describe("Zotero.Utilities.Internal", function () {
...
+			assert.lengthOf(identifiers, 4);
 			assert.lengthOf(Object.keys(identifiers[0]), 1);
-			assert.propertyVal(identifiers[0], "PMID", id);
+			assert.lengthOf(Object.keys(identifiers[1]), 1);
+			assert.lengthOf(Object.keys(identifiers[2]), 1);
+			assert.lengthOf(Object.keys(identifiers[3]), 1);
+			assert.propertyVal(identifiers[0], "PMID", "1");
+			assert.propertyVal(identifiers[1], "PMID", "24297125");
+			assert.propertyVal(identifiers[2], "PMID", "222");
+			assert.propertyVal(identifiers[3], "PMID", "123456789");
```
Comment (dstillman) [inline test/tests/utilities_internalTest.js]: Why wouldn't we want to match the `1234567890` in the above?

Comment (mrtcode) [reply test/tests/utilities_internalTest.js]: Because latest PMIDs still have 8 digits, so 9 digits are sufficient. No need to extract longer numbers.
