### PR TITLE
Allow item pane sections to declare dependencies for rerender, fix Libraries and Collections not updating

### LINKED ISSUE #4154: Libraries and Collections box doesn't update currently selected collection
When the item doesn't change.

1. Select an item in My Library
2. Add it to a collection if it isn't already in one
3. Click that collection under Libraries and Collections

My Library remains highlighted and isn't clickable.

### PR DESCRIPTION
**Pull request by AbeJellinek**
- By default, rerender is only necessary when tab or item ID changes
- Libraries and Collections box additionally depends on the collection tree row
	- Pass `collectionTreeRow` down to item pane sections

Fixes #4154

### CODE REVIEW

**Comment by windingwind** [comment]
Looks good to me!

File: chrome/content/zotero/elements/itemPaneSection.js [hunk 1]
```diff
@@ -126,12 +126,11 @@ class ItemPaneSectionElementBase extends XULElementBase {
 		let key = `_${type}RenderItemID`;
```
Comment (windingwind) [inline chrome/content/zotero/elements/itemPaneSection.js:126]: If we are setting an array to this property, maybe better to use a different name? Renaming it may also affect some tests/components.

File: chrome/content/zotero/elements/itemPaneSection.js [hunk 2]
```diff
@@ -140,10 +139,10 @@ class ItemPaneSectionElementBase extends XULElementBase {
 			return true;
 		}
 
-		if (!pendingFlag && renderFlag && newFlag === renderFlag) {
+		if (!isPending && isRendered) {
 			return true;
 		}
-		this[key] = newFlag;
+		this[key] = newDependencies;
```
Comment (windingwind) [inline chrome/content/zotero/elements/itemPaneSection.js:145]: Will break some item pane tests. We used ti rely on the _renderItemID to busy wait for rendering a specific item in the tests. (Busy wait is not very elegant, though)

**Comment by windingwind** [comment]
The item pane header seems to be broken for me

**Comment by windingwind** [comment]
The item pane header seems to be broken for me. The relevant tests fail and changes to the header mode are not applied until the next restart.

**Comment by windingwind** [comment]
Thanks for the quick fix. Seems nice!
