### PR TITLE
Don't set default attachment title if not renaming file

### LINKED ISSUE #4445: Don't set default attachment title if not renaming file
https://forums.zotero.org/discussion/comment/469170/#Comment_469170

I noticed this while testing #4431 and it seemed wrong to me. If we're not renaming a file (because auto-renaming is disabled in general or for a given file type), we shouldn't set a default title either, because the original filename may be descriptive. That's already our behavior for subsequent files.

If the person then manually uses Rename File from Parent Metadata, we can set the default title at that point.

### PR DESCRIPTION
**Pull request by AbeJellinek**
Except from Rename File from Parent Metadata.

Fixes #4445

### CODE REVIEW

File: chrome/content/zotero/zoteroPane.js [hunk 1]
```diff
@@ -5682,6 +5683,11 @@ var ZoteroPane = new function()
 				continue;
 			}
 			
+			if (item.getField('title') === oldBaseName) {
```
Comment (dstillman) [inline chrome/content/zotero/zoteroPane.js:5686]: Can you add a comment explaining this?

I'm confused by this, because if I set a PDF title to "Foo" and then run Rename File from Parent Metadata, the file still gets named as "PDF". Is that not supposed to happen? If I change the test below to set the title to "Foo", it stays that way.

Comment (dstillman) [reply chrome/content/zotero/zoteroPane.js:5686]: Merged, but would still be good to clarify this and make sure it's doing what we want.

Comment (dstillman) [reply chrome/content/zotero/zoteroPane.js:5686]: Sorry, I may have been confusing "Rename File from Parent Metadata" and "Retrieve Metadata". I'm seeing what you're seeing for Rename File, and the behavior seems right.
