### PR TITLE
Fix server not handling empty body in multi-part request. Fixes #1897 

### LINKED ISSUE #1897: SingleFIle: Broken/hanging snapshot saving on cchound.com
https://forums.zotero.org/discussion/85600/bug-report-no-snapshot-in-zotero-beta

/saveSingleFile returns a 400 with `Invalid multipart/form-data provided`, and then the connector keeps making /sessionProgress requests in perpetuity.

### PR DESCRIPTION
**Pull request by fletcherhaz**
An empty body is still valid. Was causing an issue for empty favicons.

https://forums.zotero.org/discussion/85600/bug-report-no-snapshot-in-zotero-beta

### CODE REVIEW

File: chrome/content/zotero/xpcom/server.js [hunk 1]
```diff
@@ -466,6 +466,7 @@ Zotero.Server.DataListener.prototype._processEndpoint = Zotero.Promise.coroutine
 			} else if(this.contentType === "multipart/form-data") {
 				let boundary = /boundary=([^\s]*)/i.exec(this.header);
 				if (!boundary) {
+					Zotero.debug('Invalid boundary: ' + this.header);
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/server.js:469]: Doesn't really matter, but should use a higher debug level here — probably 1 if this is equivalent to an error. Or if this is actually worth logging to the console, could just use `Zotero.logError()`.

File: chrome/content/zotero/xpcom/server.js [hunk 2]
```diff
@@ -603,17 +604,18 @@ Zotero.Server.DataListener.prototype._decodeMultipartData = function(data, bound
...
+			fieldData.header = field.slice(0, unixHeaderBoundary).trim();
+			fieldData.body = field.slice(unixHeaderBoundary+2).trim();
 		} else if (windowsHeaderBoundary != -1) {
-			fieldData.header = field.slice(0, windowsHeaderBoundary);
-			fieldData.body = field.slice(windowsHeaderBoundary+4);
+			fieldData.header = field.slice(0, windowsHeaderBoundary).trim();
+			fieldData.body = field.slice(windowsHeaderBoundary+4).trim();
 		} else {
+			// Only log first 200 characters in case the part is large
+			Zotero.debug('Malformed multipart/form-data body:' + field.substr(0, 200));
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/server.js:618]: - Missing space after `:`
- Debug level 1
