### PR TITLE
Fix document preferences dialog failing when styles unloaded.

### LINKED ISSUE #685: Display warning and (if possible) offer to install style when using document with missing style
https://forums.zotero.org/discussion/47635/

### LINKED ISSUE #1084: 5.0: Wait for style load when showing Create Bibliography window
Progress indicator in dialog?

Regardless, don't fail with a "Styles not yet loaded" exception

### LINKED ISSUE #1162: On doc prefs window error, don't set document properties
Most noticeable now because the window fails with styles not loaded (which we should also fix, along with #1084).

Possible this happens on a regular cancel as well — I didn't check.

### PR DESCRIPTION
**Pull request by adomasven**
Closes #1084

~I'm not really sure what #1162 is about, but I'd like to address it on this same branch. I could not reproduce document prefs being stored on failure.~

Edit:
Closes #1162 
Closes #685

### CODE REVIEW

**Comment by adomasven** [comment]
I've also pushed some code which will fetch the style from repo automatically. I can submit as separate PR as there might be security implications? Embed a rogue url address in the doc style id and get zotero to fetch it? Since we don't execute any JS that seems harmless enough to me. And the improvement in functionality is huge.

File: chrome/content/zotero/xpcom/style.js [hunk 1]
```diff
@@ -190,7 +190,26 @@ Zotero.Styles = new function() {
...
+				let styleText = yield Zotero.File.getContentsFromURLAsync(id, {timeout: 5000});
+				yield Zotero.Styles.install(styleText, id, true);
+				style = this.get(id, skipMappings);
+			} catch (e) {
+				Zotero.debug(`Failed to retrieve style ${id}`);
+				Zotero.debug(e);
+			}	
+		}
+		return style;
+	});
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/style.js]: I don't think this should be part of a `getAsync()`. There are lots of things that are `*Async` in Zotero now, and they don't generally kick off HTTP requests. So I think we should make this more explicit, with a separate function (`fetch` or `download` or something) that explicitly makes a request if a `get()` fails. (I also don't think this is likely to be generally necessary functionality — it's pretty specific to the case of an embedded style in a stored document.)

File: chrome/content/zotero/xpcom/style.js [hunk 2]
```diff
@@ -190,7 +190,26 @@ Zotero.Styles = new function() {
...
+		if (!style && download) {
+			try {
+				// Don't wait too long
+				Zotero.debug(`Fetching required style ${id} asynchronously`);
+				let styleText = yield Zotero.File.getContentsFromURLAsync(id, {timeout: 5000});
+				yield Zotero.Styles.install(styleText, id, true);
+				style = this.get(id, skipMappings);
+			} catch (e) {
+				Zotero.debug(`Failed to retrieve style ${id}`);
+				Zotero.debug(e);
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/style.js]: Can be `Zotero.logError(e)`

File: chrome/content/zotero/xpcom/style.js [hunk 3]
```diff
@@ -190,7 +190,26 @@ Zotero.Styles = new function() {
...
+	
+	this.getAsync = Zotero.Promise.coroutine(function* (id, skipMappings, download=true) {
+		yield this.init();
+		var style = this.get(id, skipMappings);
+		
+		if (!style && download) {
+			try {
+				// Don't wait too long
+				Zotero.debug(`Fetching required style ${id} asynchronously`);
+				let styleText = yield Zotero.File.getContentsFromURLAsync(id, {timeout: 5000});
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/style.js]: We <a href="http://docs.citationstyles.org/en/stable/specification.html#info">should be</a> checking for a `rel="self"` first, falling back to the `id`. (The whole id situation in CSL is non-ideal — the `id` would ideally be non-changing, with a (changeable) `rel="self"` for download (in which case renamed-styles.json might still be used for creating server-side `rel="link"` redirects but wouldn't be necessary for client-side resolution. But that's a discussion for elsewhere.)

/cc @rmzelle

Comment (adomasven) [inline chrome/content/zotero/xpcom/style.js]: This is not entirely on-point either, because we're getting the id from the document, where that's the only thing we store. Although this fact is a decent case to actually store rel="self" in the document prefs as well for future compatibility.

**Comment by adomasven** [comment]
> This is not entirely on-point either, because we're getting the id from the document, where that's the only thing we store. Although this fact is a decent case to actually store rel="self" in the document prefs as well for future compatibility.

Also there's issue #685 for installing missing styles and [your comment](https://forums.zotero.org/discussion/47635/) on the forums suggesting storing the link too. 

I'm not sure about the prompt:

- There's no real reason to bother users with this. In 99% of cases this should just work magically.
- If we prompt most likely response from users will be confusion and/or just clicking "install" without thinking or understanding consequences if the URL is actually weird.

Limiting to zotero.org installs and prompting for foreign styles might be a reasonable approach though. Comments?

File: chrome/content/zotero/xpcom/style.js (hunk 1 above)
Comment (adomasven) [inline chrome/content/zotero/xpcom/style.js]: > I also don't think this is likely to be generally necessary functionality — it's pretty specific to the case of an embedded style in a stored document.

Looking at this code again, I agree. I'll simplify this.

**Comment by rmzelle** [comment]
For me, it's definitely desirable to allow for auto-installing and auto-updating of styles outside of the CSL repository. Especially auto-updating. We sometimes say no to style submission to the CSL repository, and contributors are sometimes bummed that they lose the auto-update functionality already in Zotero for styles outside the official repo.

File: chrome/content/zotero/xpcom/style.js (hunk 3 above)
Comment (rmzelle) [inline chrome/content/zotero/xpcom/style.js]: > (The whole id situation in CSL is non-ideal — the id would ideally be non-changing, with a (changeable) rel="self" for download (in which case renamed-styles.json might still be used for creating server-side rel="link" redirects but wouldn't be necessary for client-side resolution. But that's a discussion for elsewhere.)

Yes, no disagreement there. There might be more old discussion on this, but this is what I could dig up:

settle on new base uri for styles, update ids accordingly
https://github.com/citation-style-language/styles/issues/2

settle on conventions for versioning
https://github.com/citation-style-language/styles/issues/7

Switch from "http" to "https" prefix for CSL style ID and "self"-links
http://xbiblio-devel.2463403.n2.nabble.com/Switch-from-quot-http-quot-to-quot-https-quot-prefix-for-CSL-style-ID-and-quot-self-quot-links-td7578982.html

call for comments on base URI issue
http://xbiblio-devel.2463403.n2.nabble.com/call-for-comments-on-base-URI-issue-td6097469.html

File: chrome/content/zotero/xpcom/style.js [hunk 4]
```diff
@@ -238,24 +238,36 @@ Zotero.Styles = new function() {
...
 	 *     displayed in dialogs referencing the style
 	 * @param {Boolean} [silent=false] Skip prompts
 	 */
 	this.install = Zotero.Promise.coroutine(function* (style, origin, silent=false) {
 		var styleTitle;
+		var warnDeprecated;
+		if (style instanceof Components.interfaces.nsIFile) {
+			warnDeprecated = true;
+			style = {file: style};
+		} else if (Object.prototype.toString.call(style) === "[object String]") {
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/style.js]: `typeof style == 'string'` is fine. (We don't need to worry about `new String()`.)

File: chrome/content/zotero/xpcom/style.js [hunk 5]
```diff
@@ -238,24 +238,36 @@ Zotero.Styles = new function() {
...
 		try {
-			if (style instanceof Components.interfaces.nsIFile) {
-				// handle nsIFiles
-				var url = Services.io.newFileURI(style);
-				var xmlhttp = yield Zotero.HTTP.request("GET", url.spec);
-				styleTitle = yield _install(xmlhttp.responseText, style.leafName, false, silent);
-			} else {
-				styleTitle = yield _install(style, origin, false, silent);
+			if (style.file) {
+				style.url = Services.io.newFileURI(style.file).spec;
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/style.js]: Should add a `style = Zotero.File.pathToFile(style);` above this line so that `file` can be a string path, which would be the preferred way to pass a file going forward. (And should update the function documentation above.)

File: test/tests/styleTest.js [hunk 6]
```diff
@@ -0,0 +1,41 @@
+"use strict";
+
+describe("Zotero.Styles", function() {
+	var styleID = "http://www.zotero.org/styles/cell";
+	var styleFile = getTestDataDirectory();
+	var style;
+	styleFile.append('cell.csl');
```
Comment (dstillman) [inline test/tests/styleTest.js]: Better to avoid `nsIFile` when it's easy to do so:

`var styleFile = OS.Path.join(getTestDataDirectory().path, 'cell.csl');`

(Then at some point we'll fix `getTestDataDirectory()` to return a string path and can just take out the `.path`.)

File: test/tests/styleTest.js [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+		style = yield Zotero.File.getContentsAsync(styleFile);
+	});
+	
+	describe("Zotero.Styles.install", function() {
+		afterEach(function* (){
+			assert.isOk(Zotero.Styles.get(styleID));
+			yield Zotero.Styles.get(styleID).remove();
+		});
+		
+		it("Installs the style from string", function* () {
```
Comment (dstillman) [inline test/tests/styleTest.js]: Lowercase, beginning with `should`, for all these. (Sorry, I know you dislike it, but that's the Mocha convention we've used for everything.)

**Comment by dstillman** [comment]
> Limiting to zotero.org installs and prompting for foreign styles might be a reasonable approach though.

Yeah, a prompt for an install that wasn't from zotero.org, citationstyles.org, or GitHub seems reasonable. It's a pretty minor privacy issue, but if you opened a doc someone sent you, had Zotero, and used the plugin, you could end up revealing your IP address to a third-party server, which I guess shouldn't happen silently.

File: test/tests/styleTest.js (hunk 6 above)
Comment (adomasven) [inline test/tests/styleTest.js]: This is literally testing nsIFile handling in this function (as I was changing the signature and wanted to make sure old calls will remain functional)

File: test/tests/styleTest.js (hunk 7 above)
Comment (adomasven) [inline test/tests/styleTest.js]: > Sorry, I know you dislike it, but that's the Mocha convention we've used for everything.

It's a bit ugly, but I strongly prefer consistency with some ugliness over ideological chaos. I simply forget that we do "should" everywhere, especially when in a new testfile, so do continue pointing it out in the future.

File: test/tests/styleTest.js (hunk 6 above)
Comment (dstillman) [inline test/tests/styleTest.js]: But this is the setup for all tests, not the `nsIFile` test, which could use `Zotero.File.pathToFile()` specifically. This way any other tests that need the file (e.g., to test passing a string path, as I suggest elsewhere) would have to convert from the deprecated `nsIFile` instead of the permanent string path.

**Comment by adomasven** [comment]
Ok. I've spent quite a bit of time on integrationTests.js in this branch, which will let me be more comfortable with further messing in integration.js. Up for review

File: chrome/locale/en-US/zotero/zotero.properties [hunk 8]
```diff
@@ -818,6 +818,7 @@ integration.error.noBibliography		= The current bibliographic style does not def
 integration.error.deletePipe			= The pipe that Zotero uses to communicate with the word processor could not be initialized. Would you like Zotero to attempt to correct this error? You will be prompted for your password.
 integration.error.invalidStyle			= The style you have selected does not appear to be valid. If you have created this style yourself, please ensure that it passes validation as described at https://github.com/citation-style-language/styles/wiki/Validation. Alternatively, try selecting another style.
 integration.error.fieldTypeMismatch		= Zotero cannot update this document because it was created by a different word processing application with an incompatible field encoding. In order to make a document compatible with both Word and LibreOffice, open the document in the word processor with which it was originally created and switch the field type to Bookmarks in the Zotero Document Preferences.
+integration.error.styleMissing			= The citation style used in this document is missing. Would you like to install it from %S
```
Comment (dstillman) [inline chrome/locale/en-US/zotero/zotero.properties]: Missing question mark at end

File: test/tests/integrationTests.js [hunk 9]
```diff
@@ -0,0 +1,322 @@
...
+					displayDialogStub.reset();
+					displayAlertStub.reset();
+				});
+				
+				after(function* () {
+					displayAlertStub.restore();
+				});
+			
+				describe('when the style is not from zotero.org or citationstyles.org', function() {
+					it('should download the style and not call doc.setDocumentData if user clicks YES', function* () {
```
Comment (dstillman) [inline test/tests/integrationTests.js]: Doesn't seem like this tests `setDocumentData`?

File: test/tests/integrationTests.js [hunk 10]
```diff
@@ -0,0 +1,322 @@
...
+					initDoc(docID, {style});
+					displayDialogStub.reset();
+					displayAlertStub.reset();
+				});
+				
+				after(function* () {
+					displayAlertStub.restore();
+				});
+			
+				describe('when the style is not from zotero.org or citationstyles.org', function() {
```
Comment (dstillman) [inline test/tests/integrationTests.js]: This isn't actually testing citationstyles.org, so shouldn't include that in the test description.

File: chrome/content/zotero/xpcom/integration.js [hunk 11]
```diff
@@ -40,6 +40,19 @@ const FORCE_CITATIONS_RESET_TEXT = 2;
...
+const DIALOG_ICON_WARNING = 1;
+const DIALOG_ICON_CAUTION = 2;
+
+const DIALOG_BUTTONS_OK = 0;
+const DIALOG_BUTTONS_OK_CANCEL = 1;
+const DIALOG_BUTTONS_YES_NO = 2;
+const DIALOG_BUTTONS_YES_NO_CANCEL = 3;
+
+const NOTE_FOOTNOTE = 1;
+const NOTE_ENDNOTE = 2;
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/integration.js]: A lot of this stuff is in the wrong commit. It would be better to move it into the previous one.

Comment (adomasven) [inline chrome/content/zotero/xpcom/integration.js]: I mean this stuff only needed moving once I started testing certain parts of integration.js, so arguably it makes just as much sense in this commit.

Comment (dstillman) [inline chrome/content/zotero/xpcom/integration.js]: It's unrelated to the problem being fixed, though, and a lot of it is just changes to the code that was introduced in the previous commit, so it pretty clearly belongs there. This is easy to fix, and it's important for people reviewing/merging code.

File: test/tests/integrationTests.js [hunk 12]
```diff
@@ -4,28 +4,21 @@ describe("Zotero.Integration", function () {
...
-			this.noteIndex = DocumentPluginDummy.Field.noteIndex++;
-			this.wrappedJSObject = this;
-		}
+	var DocumentPluginDummy = {};
+	
+	DocumentPluginDummy.Application = function() { 
+		this.doc = new DocumentPluginDummy.Document();
+		this.primaryFieldType = "Field";
+		this.secondaryFieldType = "Bookmark";
+		this.fields = [];
```
Comment (dstillman) [inline test/tests/integrationTests.js]: I meant all this stuff too. This should all go in the previous commit.

File: chrome/content/zotero/xpcom/integration.js [hunk 13]
```diff
@@ -1306,8 +1320,8 @@ Zotero.Integration.Fields.prototype.addField = function(note) {
 	var field = this._doc.cursorInField(this._session.data.prefs['fieldType']);
 	if(field) {
 		if(!this._doc.displayAlert(Zotero.getString("integration.replace"),
-				Components.interfaces.zoteroIntegrationDocument.DIALOG_ICON_STOP,
-				Components.interfaces.zoteroIntegrationDocument.DIALOG_BUTTONS_OK_CANCEL)) {
+				DIALOG_ICON_STOP,
+				DIALOG_BUTTONS_OK_CANCEL)) {
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/integration.js]: This should go with the same commits as the constants.

File: test/tests/styleTest.js [hunk 14]
```diff
@@ -12,7 +12,7 @@ describe("Zotero.Styles", function() {
 	});
 	
 	describe("Zotero.Styles.install", function() {
-		afterEach(function* (){
+		afterEach(`${styleID} style should be installed`, function* (){
```
Comment (dstillman) [inline test/tests/styleTest.js]: This actually works?

File: test/tests/integrationTests.js [hunk 15]
```diff
@@ -262,8 +262,9 @@ describe("Zotero.Integration", function () {
 					displayAlertStub.restore();
 				});
 			
-				describe('when the style is not from zotero.org or citationstyles.org', function() {
+				describe('when the style is not from a trusted source', function() {
```
Comment (dstillman) [inline test/tests/integrationTests.js]: Are we actually doing something different for untrusted sources at this point?

File: test/tests/styleTest.js (hunk 14 above)
Comment (adomasven) [inline test/tests/styleTest.js]: What? The string? Yeah, if the assertion fails in the hook it displays this string. Was reading mocha docs the other day and got surprised myself.

File: test/tests/integrationTests.js (hunk 15 above)
Comment (adomasven) [inline test/tests/integrationTests.js]: As described in the 3 following tests. Prompt if untrusted source, install without prompt otherwise.

Comment (dstillman) [inline test/tests/integrationTests.js]: Ah, sorry, got my negation (and waterbirds) confused.
