### PR TITLE
Recognizes and opens files even without extensions.

### LINKED ISSUE #842: Opening PDF with stored 'application/pdf' but no .pdf extension doesn't work
Instead of the PDF being displayed internally in pdf.js, a messed-up open/save dialog is shown:

dialog

### PR DESCRIPTION
**Pull request by adomasven**
Closes #842

Also:
Changes AsyncChannel to be a coroutine. Couldn't find any tests for it, but Dan said it was okay to do it and testing on the attachment types I have seems to be fine.

### CODE REVIEW

File: components/zotero-protocol-handler.js [hunk 1]
```diff
@@ -767,6 +767,7 @@ function ZoteroProtocolHandler() {
 							}
 						}
 					}
+					file.extension
```
Comment (dstillman) [inline components/zotero-protocol-handler.js]: Stray line?

File: components/zotero-protocol-handler.js [hunk 2]
```diff
@@ -1230,9 +1225,8 @@ AsyncChannel.prototype = {
 					Zotero.debug("AsyncChannel: Got URI from generator");
 				}
 				
-				let uri = data;
-				uri.QueryInterface(Ci.nsIURL);
-				this.contentType = Zotero.MIME.getMIMETypeFromExtension(uri.fileExtension);
+				let sample = yield Zotero.File.getSample(data);
+				this.contentType = Zotero.MIME.getMIMETypeFromData(sample);
```
Comment (dstillman) [inline components/zotero-protocol-handler.js]: If there's an extension, try `getMIMETypeFromExtension` first, to avoid reading the file unnecessarily?

**Comment by adomasven** [comment]
Adjusted. Force-pushed
