### PR TITLE
Fix/sync auth form

### LINKED ISSUE #833: Warn before syncing into an empty library
We should make sure we warn before syncing into a new library. It's impressive when it just works, but it causes too much confusion when people, say, move a data directory without disabling auto-sync.

(I think right now we only warn when the userID changes.)

### LINKED ISSUE #886: Auth form shown in sync prefs until key info check finishes
Looks like this is still happening. Instead, if there's a DB username and API key it should show the status as linked until it knows for sure otherwise.

Follow-up from #879

### PR DESCRIPTION
**Pull request by adomasven**
Closes #886 
Closes #833 

Did not really require `Zotero.Library.hasItems` method, but I had implemented it before (my idea was to check for absence of items in current library and presence of items on the sync server), so we may as well keep it - might come in handy.

### CODE REVIEW

**Comment by dstillman** [comment]
Instead of running a query to update `hasItems` on every item addition/deletion, we should just run a query on-demand in `Zotero.Library::hasItems()`, which will be called at sync time when there's no userID.

(Also, this will need to be rebased on top of my WebDAV commit — sorry.)

File: chrome/content/zotero/xpcom/sync/syncRunner.js [hunk 1]
```diff
@@ -230,6 +236,24 @@ Zotero.Sync.Runner_Module = function (options = {}) {
...
+
+		if(!userID && !library.hasItems()) {
+			if(! Services.prompt.confirm(
+				null,
+				Zotero.getString('general.warning'),
+				Zotero.getString('sync.warning.emptyLibrary', Zotero.clientName)
+			)) {
+				return false;
+			}
+		}
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/sync/syncRunner.js]: We generally avoid `confirm`, because it doesn't provide control over the button titles. Should use `confirmEx` with `sync.sync` and either `sync.cancel` or just "Cancel".

**Comment by adomasven** [comment]
I had worked more with different zotero items since and realized, that `updateItems`/`hasItems` could possibly include attachments and notes as well, since they can be top-level. Is this correct and should I update accordingly?

**Comment by adomasven** [comment]
Changes pushed.

**Comment by dstillman** [comment]
Not sure what you mean about attachments and notes, but isn't this still running an extra query on every item addition/deletion?

I don't think we need/want an `updateItems` at all, and I don't think we need this to be library-specific. I think there could just be a single function with no parameters that does a `COUNT(*) > 0` for items across the whole DB. I'm not sure where that should go — maybe `Zotero.Items.hasItems()`?

**Comment by adomasven** [comment]
Whoops, didn't remove `updateItems` calls where I should have. 

I created `hasItems` in line with `hasCollections` and `hasSearches`, which then made sense to have them in `Zotero.Library`. In general, I still think it might make more sense to have a per-library `hasItems` function as it could come in handy in the future. Something which does `COUNT(*) > 0` for all items would probably be less versatile.

File: chrome/locale/en-US/zotero/zotero.properties [hunk 2]
```diff
@@ -828,6 +828,7 @@ sync.localDataWillBeCombined		= If you continue, local Zotero data will be combi
 sync.localGroupsWillBeRemoved1		= Local groups, including any with changed items, will also be removed from this computer.
 sync.avoidCombiningData				= To avoid combining data, revert to the '%S' account or use the Reset options in the Sync pane of the Zotero preferences.
 sync.unlinkWarning					= Are you sure you want to unlink this account?\n\n%S will no longer sync your data, but your data will remain locally.
+sync.warning.emptyLibrary			= Your are about to sync to an empty %1$S database. This might be due to a new installation %1$S or the location of your data directory changing.\n\nDo you want to continue?
```
Comment (dstillman) [inline chrome/locale/en-US/zotero/zotero.properties]: This actually shouldn't happen for a new Zotero installation, because a new installation will need to set the userID in the prefs before syncing, right? So this would only be a new database, either from a deleted previous database or a new data directory, with an existing Firefox or Zotero profile with an API key stored.

I also think we should provide a third button to open the data dir prefs.

sync.warning.emptyDatabase = You are about to sync the ‘%1$S’ account to an empty %2$S database. This could happen if you removed your previous %2$S database or if the location of your data directory changed.
sync.warning.existingDataElsewhere = If your %1$S data exists elsewhere on your computer, you should move it to your current data directory or change your data directory location to point to the existing data.

dataDir.changeDataDirectory = Change Data Directory…

File: chrome/content/zotero/xpcom/sync/syncRunner.js [hunk 3]
```diff
@@ -230,6 +236,24 @@ Zotero.Sync.Runner_Module = function (options = {}) {
...
 	});
+
+
+	// Prompt if library empty and there is no userID stored
+	this.checkEmptyLibrary = Zotero.Promise.coroutine(function* (client) {
+		let library = Zotero.Libraries.userLibrary;
+		let userID = Zotero.Users.getCurrentUserID();
+
+		if(!userID && !library.hasItems()) {
+			if(! Services.prompt.confirm(
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/sync/syncRunner.js]: Style: no space after `!`

Comment (dstillman) [inline chrome/content/zotero/xpcom/sync/syncRunner.js]: Oops, outdated diff, but same note for a bunch of different places

File: chrome/content/zotero/xpcom/data/library.js [hunk 4]
```diff
@@ -567,6 +570,22 @@ Zotero.Library.prototype.updateSearches = Zotero.Promise.coroutine(function* ()
 	this._hasSearches = !!(yield Zotero.DB.valueQueryAsync(sql, this.libraryID));
 });
 
+Zotero.Library.prototype.hasItems = Zotero.Promise.coroutine(function* () {
+	if (! this.id) {
+		throw new Error("Library is not saved yet");
+	}
+	if (this._hasItems === null) {
+		yield this.updateItems();
+	}
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/data/library.js]: This will never be run, because `hasItems` is populated during library load. We can have a per-library hasItems — that's not technically the test we want for this, but I think it wouldn't matter because you can't have groups without a userID, and not having a userID is a prereq for this to be called — but it should still be run on-demand and not cached, since we're not updating it like the other two.

Right now, if you delete the DB, sync, get the warning, cancel, create a new item (or import thousands of items), and sync again, you get the warning again.

File: chrome/locale/en-US/zotero/zotero.properties (hunk 2 above)
Comment (adomasven) [inline chrome/locale/en-US/zotero/zotero.properties]: Ah yes, I wrote this string when I thought I'd check with the remote repository whether there were any items there and haven't updated for logic changes.

File: chrome/locale/en-US/zotero/zotero.properties [hunk 5]
```diff
@@ -828,6 +829,8 @@ sync.localDataWillBeCombined		= If you continue, local Zotero data will be combi
 sync.localGroupsWillBeRemoved1		= Local groups, including any with changed items, will also be removed from this computer.
 sync.avoidCombiningData				= To avoid combining data, revert to the '%S' account or use the Reset options in the Sync pane of the Zotero preferences.
 sync.unlinkWarning					= Are you sure you want to unlink this account?\n\n%S will no longer sync your data, but your data will remain locally.
+sync.warning.emptyLibrary			= Your are about to sync your account to an empty %1$S database. This could happen if you removed your previous %1$S database or if the location of your data directory changed.
```
Comment (adomasven) [inline chrome/locale/en-US/zotero/zotero.properties]: Says *your account* instead of *the '%1$S' account*, because with empty database there is no reliable way to get the account. We could use prefs, but it does not have to be populated.

Comment (dstillman) [inline chrome/locale/en-US/zotero/zotero.properties]: Sorry, meant to clarify — we can just move the check after `checkAccess`, such that we'll already have `keyInfo.username`, right?

**Comment by adomasven** [comment]
Amended.

File: chrome/content/zotero/xpcom/data/library.js [hunk 6]
```diff
@@ -305,6 +307,7 @@ Zotero.Library.prototype._loadDataFromRow = function(row) {
 	
 	this._hasCollections = !!row.hasCollections;
 	this._hasSearches = !!row.hasSearches;
+	this._hasItems = !!row.hasItems;
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/data/library.js]: Remove

File: chrome/content/zotero/xpcom/data/library.js [hunk 7]
```diff
@@ -79,6 +80,7 @@ Zotero.defineProperty(Zotero.Library, '_rowSQLSelect', {
 	value: "L.libraryID, " + Zotero.Library._dbColumns.map(function(c) "L." + c + " AS " + Zotero.Library._colToProp(c)).join(", ")
 		+ ", (SELECT COUNT(*)>0 FROM collections C WHERE C.libraryID=L.libraryID) AS hasCollections"
 		+ ", (SELECT COUNT(*)>0 FROM savedSearches S WHERE S.libraryID=L.libraryID) AS hasSearches"
+		+ ", (SELECT COUNT(*)>0 FROM items I WHERE I.libraryID=L.libraryID) as hasItems"
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/data/library.js]: Remove

File: chrome/content/zotero/xpcom/data/library.js [hunk 8]
```diff
@@ -33,6 +33,7 @@ Zotero.Library = function(params = {}) {
 	
 	this._hasCollections = null;
 	this._hasSearches = null;
+	this._hasItems = null;
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/data/library.js]: Remove

File: chrome/content/zotero/xpcom/data/library.js [hunk 9]
```diff
@@ -567,6 +570,16 @@ Zotero.Library.prototype.updateSearches = Zotero.Promise.coroutine(function* ()
 	this._hasSearches = !!(yield Zotero.DB.valueQueryAsync(sql, this.libraryID));
 });
 
+Zotero.Library.prototype.hasItems = Zotero.Promise.coroutine(function* () {
+	if (!this.id) {
+		throw new Error("Library is not saved yet");
+	}
+	let sql = 'SELECT COUNT(*)>0 FROM items WHERE libraryID=?';
+	let hasItems = !!(yield Zotero.DB.valueQueryAsync(sql, this.libraryID));
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/data/library.js]: return directly

File: chrome/content/zotero/xpcom/sync/syncRunner.js [hunk 10]
```diff
@@ -231,6 +237,39 @@ Zotero.Sync.Runner_Module = function (options = {}) {
 		
 		return json;
 	});
+
+
+	// Prompt if library empty and there is no userID stored
+	this.checkEmptyLibrary = Zotero.Promise.coroutine(function* (keyInfo) {
+		let library = Zotero.Libraries.userLibrary;
+		let userID = Zotero.Users.getCurrentUserID();
+		let hasItems = yield library.hasItems();
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/sync/syncRunner.js]: This should be a very quick query, but still no reason to run it unless `!userID`.

File: chrome/content/zotero/xpcom/data/item.js [hunk 11]
```diff
@@ -3710,6 +3710,12 @@ Zotero.Item.prototype._eraseData = Zotero.Promise.coroutine(function* (env) {
 });
 
 
+Zotero.Item.prototype._finalizeErase = Zotero.Promise.coroutine(function* (env) {
+	yield Zotero.Item._super.prototype._finalizeErase.call(this, env);
+
+});
+
+
```
Comment (dstillman) [inline chrome/content/zotero/xpcom/data/item.js]: Remove

**Comment by adomasven** [comment]
Ah, sorry about those leftovers! Should be doing these things on my own before committing!

**Comment by dstillman** [comment]
I was actually thinking it was better to just cancel the sync and send people to the prefpane, since if we use `chooseZoteroDirectory()` directly you can't see what the current directory is and you can't toggle between the default dir and a custom one. When people encounter this and don't want to go ahead with the sync, there's a decent chance there's some confusion or uncertainty where the extra context that the prefpane provides might be helpful.

**Comment by dstillman** [comment]
(Oh, and also can't use Show Data Directory, which might be necessary for moving stuff to the right place.)

**Comment by adomasven** [comment]
Pushed

File: chrome/locale/en-US/zotero/zotero.properties [hunk 12]
```diff
@@ -828,6 +829,8 @@ sync.localDataWillBeCombined		= If you continue, local Zotero data will be combi
 sync.localGroupsWillBeRemoved1		= Local groups, including any with changed items, will also be removed from this computer.
 sync.avoidCombiningData				= To avoid combining data, revert to the '%S' account or use the Reset options in the Sync pane of the Zotero preferences.
 sync.unlinkWarning					= Are you sure you want to unlink this account?\n\n%S will no longer sync your data, but your data will remain locally.
+sync.warning.emptyLibrary			= Your are about to sync the ‘%1$S‘ account to an empty %2$S database. This could happen if you removed your previous %2$S database or if the location of your data directory changed.
```
Comment (dstillman) [inline chrome/locale/en-US/zotero/zotero.properties]: `‘%1$S’`

Comment (dstillman) [inline chrome/locale/en-US/zotero/zotero.properties]: and "You are"

**Comment by dstillman** [comment]
All right, can squash. (For the individual commits, when referencing a ticket, be sure it also says what's being fixed. Usually that's as simple as "Closes #nnn, <title of #nnn>", if it's short enough. That way a git log doesn't require going to GitHub to see what was fixed.)

**Comment by adomasven** [comment]
Squished and pushed.
